y-lohse/inkjs

engine/Story.js
.Push on the callstack object should be capitalised!
=> Fixes to uncapitalised Push methods

engine/Story.js
Need to explicitly set overrideTunnelReturnTarget to null if its void as we're missing the cast that C# does
=> Fix for overrideTunnelReturnTarget being Void

engine/StoryState.js
The following ink source: 
=== function not_working() ===
Text1.
Text2.
~ return true
in conjunction with a call like 
story.EvaluateFunction("not_working");
from the javascript file running the game causes an error when the ~ return statement is encountered as it's unexpected.
Note the C# doesn't seem to copy this property explicitly, but it is correct and does the fix the issue.
=> Fix for ink functions called from game code

engine/StoryState.js
The case of the ToJson function is wrong. It's different from the C# implementation of Ink and from their documentation.
=> Correcting case of toJson to ToJson

engine/InkList.js
If you look at get fullName(), there's supposed to be a "." between the origin and the item names. InkLists can't be loaded correctly back from JSON without the period. 
There are two toString() methods in this class, but I'm assuming that was intentional.
=> Saving of InkList is not working correctly

engine/StoryState.js
On completion of an external function, unset the flag that tells the engine we're in an externally called function.
=> Unset the "in external evaluation" flag

engine/Story.js
The intVal parameter was already casted to a normal int, but then trying to use ".value" to read its value.
=> Fix for ListFromInt

engine/CallStack.js, engine/Choice.js, engine/Container.js, engine/Divert.js, engine/JsonSerialisation.js, engine/Object.js, engine/Path.js, engine/Pointer.js, engine/SearchResult.js, engine/StringBuilder.js, engine/Value.js
This PR fixes a number of small typos that I've encountered while running the tests.
Merging it after #171 might introduce some mess in the history, so I'll rework the PR if that's the case.
Side note: I've added a `copy` method to `SearchResult` in order to highlight the fact that it's a value-type. It's not used anywhere.
=> fix: correct typos and indentation on multiple files

engine/Value.js
Fixes part 2 of https://github.com/y-lohse/inkjs/issues/200. There's actually a bug in the compiler that is producing empty string values, but inkjs wasn't handling them the same as the C# ink, not that they should ever exist!
=> Fix handling of empty string values

package.json
Reverts y-lohse/inkjs#208
While the PR was green, the merge broke the build. I'll have to investigate.
=> Revert "chore(deps): update dependency rollup-plugin-babel to v4"

src/JsonSerialisation.js, src/TypeAssertion.ts, src/Value.ts, src/VariableAssignment.ts, src/VariablesState.ts
This PR completes #193.
Thanks for reviewing!
=> Variables State

src/VariablesState.ts
This missing line was breaking the variable observers.
=> variableChangedEventCallbacks now preserved when VariableState is copied

.codecov.yml, .travis.yml, jest.config.js, package-lock.json, package.json, tests/common.js
Minor changes, to run the tests three time. Once for coverage, once on the default file and one last time on the legacy file.
This is a WIP, because I'd like to show off the coverage metrics. @y-lohse how do you feel about adding a coverage shield to the README and coverage checks for PR? Is there a specific service you like?
=> Run tests three times (transpiled source, minified file and legacy file)

src/VariablesState.ts
Just fixing the typo (`InkObject` -> `any`) raised by #469.
=> Fix #469 (VariablesState.SetGlobal typedef is overly narrow)

src/TypeAssertion.ts, src/VariablesState.ts
I completed what @y-lohse started (and practically finished at the time). Three things to take note about:
1. I replaced `== null` by `=== null`, I don't think it makes much difference, but I think we have strict equality almost everywhere else. I hope that's okay!
2. I added `isEquatable` in `TypeAssertion.ts`, so that `RuntimeObjectsEqual` can compare `Inklist` and `Path` using `Equals` while using `===` for anything else.
3. I moved `SetJsonToken` and `ApplyStatePatch` up, so they match the position of their C# counterparts. Was there a reason for them to be at the bottom?
Also, we have three different ways of converting `TryGet` calls 😂. We really need to settle on one syntax!
=> [v0.9] VariablesState.ts

tests/specs/ink/Logic.spec.js
After #515, this disabled test is now passing \o/
=> Activate disabled print_num test

src/engine/Path.ts, src/engine/Story.ts, src/engine/StoryState.ts
Fixes #176 
The orignal code uses `Collection.AddRange` in several places, and using `Array.push.apply` was only one of the workarounds. There may be other places that could benefit from destructuring parameters passed to `Array.push`.
=> fix: Remove calls to Array.push.apply

.babelrc, package-lock.json, package.json
We don't really need to specify plugins manually, `babel-env` can detect what is required… provided we give it a browserlist, which this PR does.
(Also we don't use Object.assign anywhere anymore…)
=> chore: Use babel-env only for configuration

src/engine/DebugMetadata.ts
I remember that code, I wrote it. 😎
It's not particularly needed by inkjs (it's a compiler thing), but I feel that if we don't migrate it, it'll cause some confusion down the line.
=> feat: migrate DebugMetadata.ts

src/engine/InkList.ts
Very straightforward.
I also uncommented `Story`, left over from the TypeScript migration.
=> feat: migrate InkList.ts

CONTRIBUTING.md
I finally came around to create a `CONTRIBUTING.md`! I've been meaning to do this for a while, but I was lazy.
I plan to roughly formalise the migration rules (how to port certain structures), as well as the quirks we have in inkjs (such as testing against null to please TypeScript.
Let me know what you think!
=> docs: add CONTRIBUTING.md and start documenting the migration process

CONTRIBUTING.md, src/engine/Error.ts, src/engine/Story.ts
There's a lot more changes than in the last few PR.
- The new Error Handler / Callbacks are types as `Function | null`, instead of just being optional, so that it matches the C# code better.
- There'a couple of errors, I'll fix them once `StoryState` is ported.
- The original integer overflow logic is different.
- I've tweaked the logic in `RemoveVariableObserver`, if I remember correctly a kind contributors created a PR in both repos, but the TypeScript code didn't seemt to match upstream. You may want to have a hard look at this.
=> feat: migrate Story.ts

.github/workflows/npm-publish.yml
It looks like we've never published ink.js since we switched to github actions, and apparently there was a bug in the action configuration. I've updated the file according to the latest version of the official docs, let's see how this goes.
=> chore: Update publication workflow

.github/workflows/npm-publish.yml
#878 worked but after seeing the workflow in action. I realize that both jobs run in parallel, but the publish step should run only if the test job is successful. So really the initial config was almost correct, except that `needs` should have been `test` and not `build`.
=> chore: Run tests before publishing

package.json
When trying to install the package from GitHub, I found that the built JavaScript files were missing! This adds that build step in by switching the `prepublishOnly` script to `prepare`.
Admittedly, this also means that running `npm install` in the repo's directory during development will always build the full JS. I'd like to make that build even faster 👹, but until then: `npm install --ignore-scripts` is the way to go.
=> Switch `prepublishOnly` to `prepare` to allow for git installation

ink.d.ts, rollup.config.js
ES modules need a default export to function properly with other es modules.  Since this project is modern and uses modules under the hood, it was simple enough to add support by adding an additional export in the entry point along with the corresponding rollup build step. 
All tests pass, however there were some existing lint issues that remain from the moment of the fork to the modifications. 
Thanks!
=> [request] add es6 module support

src/compiler/Parser/InkParser.ts, src/compiler/Parser/StringParser/StringParser.ts, src/compiler/Parser/StringParser/StringParserElement.ts
The `characterInLineIndex` property of debugMetadata was not computed (oversight in the port) _and_ the other properties were exposed incorrectly, leading to the wrong line being reported when a parsing error occured.
To be merged in https://github.com/y-lohse/inkjs/pull/937
=> Port missing characterInLineIndex in debugMetadata

README.md, docs/working-with-typescript-and-webpack.md
- [] The linter ran and found no issues (`npm run-script lint`).
The linter did find issues that aren't fixed, but they aren't in files I've touched for this PR.
This adds a markdown file to the documentation that explains how to configure Webpack to load ink files and how to configure TypeScript to recognise them.
The linter has also gone to town on README.md (which I added a link to the new document to).
=> Document webpack typescript

templates/browser_serverless/main.js, templates/browser_serverless/style.css, templates/browser_with_server/main.js, templates/browser_with_server/style.css
The [`prefers-reduced-motion` media query](https://css-tricks.com/introduction-reduced-motion-media-query/) allows users to specify an accessibility setting for less animation. The purpose of this PR is to respect this setting.
…but I'm cheating: these scripts don't look at template files.
When the user requests reduced animations, disable:
- Scrolling: Smooth scrolling triggers seasickness, so disable it. Instant scrolling is usually preferred but would be disorienting in the context of Ink games. Instead, let the user scroll at their own pace.
- Fade-in: A row of flashing paragraphs can also be a vestibular trigger. Show all the paragraphs at once.
[PR for Inky](https://github.com/inkle/inky/pull/427) with similar changes.
=> Disable web animations when the user prefers reduced motion

src/engine/InkList.ts
This is a port of inkle/ink commit af9ec78.
The ink script 
```
LIST ListA = a, b, c 
LIST ListB = (p), q, r
{LIST_ALL(ListA)} 
~ addStates()
{LIST_ALL(ListA)} 
=== function addStates 
~ return ListA + ListB 
```
previously generated
```
a, b, c
p, q, r
```
It should generate 
```
a, b, c
a, b, c
```
=> Fix: accidentally cloning origin names when constructing a list

script/inkjs-compiler.ts, src/compiler/FileHandler/PosixFileHandler.ts
This fixes a couple of problems I ran into when trying to run `inkjs-compiler` on Ink source split across multiple files:
- Adds a basic error handler that prints errors to process.stderr
- Don't mangle filenames in `PosixFileHandler`
The file handler was removing the current directory from anywhere in the filename, which is definitely incorrect (e.g. if the current directory is "." it will remove all dots from the filename).
I guess the intention may have been to the remove the current directory from the start of the filename, but I don't think that's correct either — it would break if the working directory were say `ink` and we tried to include `ink/ink/foo.ink`.
So, this PR just interprets the filename as being relative to the working dir, which does the right thing for my use case.
=> Fix INCLUDE paths in inkjs-compiler

src/engine/StoryState.ts
This method was calling [substring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) with (start, length) instead of (start, end).
I ran into this with an ink file including command output that looks like this: `\nFoo bar`. It would print `Foo ba` instead of `Foo bar`.
I'm not an ink expert, so I could use some help adding a unit test for this!
=> Fix incorrect substring in TrySplittingHeadTailWhitespace

src/compiler/FileHandler/PosixFileHandler.ts
Initialize rootPath with a default value (empty string), and use path.resolve() to construct an absolute path. If an absolute path is provided, that will be used. if a relative path is provided, it will append that to the working directory.
=> simplify POSIX file handler

src/compiler/Parser/CharacterRange.ts
The `CharacterRange.ToCharacterSet` method returns only the first character defined by CharacterRange. Therefore, `InkParser.ExtendIdentifierCharacterRanges` extends `identifierCharSet` only with the first character of each character set.
This pull request fixes the `ToCharacterSet` method behavior, returning all characters from CharacterRange.
=> inkjs-compiler: fix non-ascii identifiers

src/compiler/Parser/ParsedHierarchy/Argument.ts, src/compiler/Parser/ParsedHierarchy/IncludedFile.ts
adds a few extra `typeName`s to classes that lacked them
=> add additional typeName fields to ParsedHierarchy objects

src/compiler/Compiler.ts
Adds `Parser` and `StatementLevel` to the exports of the full bundle, so that they are accessable to other packages.
This does not increase the bundle size
=> include Parser and StatementLevel in full bundle exports

src/compiler/Parser/InkParser.ts
- **Quelques warnings mais ils étaient là avant.**
This PR fixes a bug in the compiler with empty INCLUDEs.
Example:
```
// main.ink
INCLUDE a.ink
INCLUDE b.ink
{foo}
// a.ink (empty file)
// b.ink
VAR foo = "bar"
```
If you compile it with the inkjs.Compiler and a correctly set-up JsonFileHandler, the story fails at run-time with `Unresolved variable: foo`.
If `a.ink` is not empty (a single space character is enough), everything works as expected.
This bug is caused by a falsy value ("") not taking the correct branch in an if statement `if (includedString)`. This PR fixes that if with a stricter check: `if (includedString != null)`.
=> fix: correctly handle empty INCLUDEs

src/engine/Story.ts
Probably a copy-paste error when duplicating the code from `minInt` (a few lines above) for `maxInt`.
The instanceof check should be on maxInt.
=> Fixed maxInt type check in RANDOM

ink.d.ts
As described in #959, there is an incompatibility between how this declaration file is structured and the expectations of recent TypeScript versions.
Removing the export assignment ensures that only the default symbol is exported.
```
An export assignment cannot be used in a module with other exported elements.
```
Perhaps a better long term solution would be to upgrade the version of TypeScript used in the project. Happy to help with this if I can get a bit of guidance around where to start and managing build tools.
=> Remove export assignment from ink.d.ts

ink.d.ts
Fixes a problem introduced in #1049 where the relative imports changed to suit standalone references to these files on disk—but overlooked that the tsconfig had `src` already mapped.
=> Fix imports and add docblocks

script/inkjs-compiler.ts, src/engine/ControlCommand.ts, src/engine/Void.ts
All playing a json file on the command line (was previously limited to playing an uncompiled ink file)
=> Allow playing a json file

package.json, src/engine/Story.ts, src/tests/inkfiles/original/choices/dynamic_tags_in_choice.ink, src/tests/specs/ink/Choices.spec.ts
Fixes https://github.com/y-lohse/inkjs/issues/1047
=> Put dynamic tags in choice in correct order

.github/workflows/checks.yml, .github/workflows/npm-manual-publish.yml, .github/workflows/npm-publish.yml, ink.d.mts, package.json, rollup.config.js
- Publish es6 package with mjs extension
-  fix errors in package.json declared on [publint](https://publint.dev/inkjs@2.2.3) 
- declare type "commonjs" 
- add `exports` with `import` and `default` version
- Upgrade github pipeline to Node20
=> Publish es6 as mjs and declare type

src/engine/StoryState.ts, src/tests/specs/inkjs/engine/Integration.spec.ts
(there were pre-existing warnings)
`PassArgumentsToEvaluationStack` checks that arguments are valid and reports an error if not.
There are two bugs in this function:
- the arguments to validate are in the `args` variable but this function incorrectly uses the special `arguments` keyword instead in two places in the error reporting section
- the ternary operator is incorrectly parenthesised, causing the thrown error to always be `new Error("null")`
I've added two tests to check that an invalid parameter passed to a function or a knot/stitch is correctly reported.
=> Fixed arguments error reporting

README.md
Only README was changed 
Correct imports in the documentation
=> Update README.md with imports

src/compiler/Compiler.ts, src/compiler/Stats.ts, src/tests/specs/inkjs/compiler/Stats.spec.ts
Adding stats generation from the ink compiler to inkjs. The ink compiler only exposes this as a command line option, but for inkjs I've exposed it as a new function in the Compiler that can be run after compilation.
For source from the ink repository, see https://github.com/inkle/ink/blob/master/compiler/Stats.cs
=> Added stats generation

package-lock.json, src/engine/VariablesState.ts, src/tests/specs/ink/Bindings.spec.ts
https://github.com/y-lohse/inkjs/issues/1058
You can now list all global variables (`VAR` and `LIST`) using `Object.keys(story.variableState)`
=> list global variables using Object.keys

src/engine/StoryState.ts, src/tests/specs/ink/Evaluation.spec.ts
https://github.com/y-lohse/inkjs/issues/1099
`Path` is not a publicly exposed class in js. So I suggest we prefix any DivertTarget with a `-> `
=> Prefix -> in front of divertTarget when using EvaluateFunction

src/compiler/IFileHandler.ts, src/compiler/Parser/InkParser.ts
Add a `sourceFilename` parameter to the `ResolveInkFilename` and `LoadInkFileContents` methods of the `IFileHandler`. These will provide context to the IFileHandler to be able to resolve the actual Include Filename, relative to the Source Ink Filename that included it. This is particularly useful when an Ink Story has Include Files that, in themselves, also Include Files.
For example, `/main.ink` includes `/common/functions.ink`, which includes `/common/library/my_function.ink`, this would open the door to define as follows:
```/main.ink
INCLUDE common/functions.ink
```
```/common/functions.ink
INCLUDE library/my_functions.ink
```
This PR is being proposed in support of a [VSCode Extension for Ink](https://github.com/bemisguided/vscode-ink-language-tools) under-development.
On Discord, we …
=> feat: compiler: add source filename to the IFileHandler
